services:
  backend:
    build:
      context: ./backend
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres.zwrfxfbtdwzaerxdcgnr:26599489Abc@aws-1-us-east-2.pooler.supabase.com:5432/postgres
    restart: always

networks:
  default:
    name: fsm-index-network
